### ISSUE TITLE
What do you use header2whatever for?

### ISSUE THREAD

**Issue by auscompgeek** [lnstempunks/MarvinTheParanoidAndroid#3]
I was looking at some of RobotPy's dependency trees on GitHub, and saw that this repo has header2whatever listed as a direct dependency. I was wondering what you use it for.

**Comment by Tyler-Duckworth** [comment]
Sorry for the late response!

At this time, we don't exactly know what we were using it for. We had converted this project to a PIPENV and this was on the `requirements.txt`, so I assume someone might have used this at one point. 

Right now, it isn't being used for anything, so we have removed it. Sorry for all the confusion.

**Comment by Tyler-Duckworth** [comment]
``
